spring:
  application:
    name: kafka-micro

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: player-command-processor  # группа consumer'ов
      auto-offset-reset: earliest
      enable-auto-commit: false            # ручное подтверждение
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.kafkamicro.dto"
        spring.json.type.mapping: "com.example.practice.dto.PlayerCommand:com.example.kafkamicro.dto.PlayerCommand"

server:
  port: 8097

# Адрес dbmicro (используется в CommandProcessorService)
dbmicro:
  api:
    url: ${DBMICRO_URL:http://host.docker.internal:8096/api/players}

# Настройки топиков
kafka:
  topics:
    player-commands: player-commands   # топик, который слушаем

logging:
  level:
    com.example.kafkamicro: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"