# application.properties
spring.application.name=practice
server.port=8095

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui

# ???????? ??????? ?? ?????????
#spring.profiles.active=dev
spring.profiles.active=prod

# Swagger
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.cache.disabled=true

# Spring Boot
server.error.whitelabel.enabled=false

#  stacktrace
server.error.include-stacktrace=never
server.error.include-message=on_param
server.error.include-binding-errors=never

spring.web.resources.add-mappings=false

logging.level.org.springframework.cache=TRACE
logging.level.org.springframework=DEBUG
logging.level.root=ERROR